version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: muscles
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/mongo

volumes:
  mongodb_data_container:
